-- The catalogue as the site had it before the admin page (made by tools/seed.mjs).
-- Only fills an empty catalogue, so it never undoes changes made in the admin.
do $$
begin
  if exists (select 1 from public.products) or exists (select 1 from public.categories) then return; end if;
  insert into public.categories (key, name, sort) values ('cooking', 'Cooking', 0);
  insert into public.categories (key, name, sort) values ('prep', 'Food Preparation', 1);
  insert into public.categories (key, name, sort) values ('beverage', 'Beverage', 2);
  insert into public.categories (key, name, sort) values ('cookware', 'Cookware & Tableware', 3);
  insert into public.categories (key, name, sort) values ('home', 'Home Care', 4);
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('microwave-25l', 'GP Microwave Digital 25L', 'cooking', null, 'Kitchen Appliances, Microwaves', 'Digital 25 litre microwave with preset cooking programmes.', 'A 25 litre digital microwave built for daily family cooking. Touch controls, preset programmes and a clear interior light, finished in matte black so it sits quietly on an open counter.', '[["Capacity","25 litres"],["Control","Digital touch panel"],["Programmes","Preset auto cook"],["Finish","Matte black"]]'::jsonb, 0, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('air-fryer-6-5l', 'GP Air Fryer 6.5L', 'cooking', null, 'Kitchen Appliances, Air Fryers', 'Large 6.5 litre basket with a viewing window and steel trim.', 'A 6.5 litre air fryer sized for a full family meal in one basket. Rapid hot air circulation, a viewing window on the drawer and a brushed steel front that wipes clean.', '[["Capacity","6.5 litres"],["Drawer","Viewing window"],["Body","Steel and matte black"],["Use","Fry, roast, bake"]]'::jsonb, 1, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('air-fryer-dual-11-6l', 'GP Dual Air Fryer 11.6L', 'cooking', null, 'Kitchen Appliances, Air Fryers', 'Two independent baskets, 11.6 litres of total capacity.', 'Two separate drawers in one body, so a main and a side cook at the same time at their own temperature. A digital panel across the top controls both baskets, in an all black finish.', '[["Capacity","11.6 litres total"],["Baskets","Two, independent"],["Control","Digital touch panel"],["Finish","Gloss black"]]'::jsonb, 2, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('electric-oven-50l', 'GP Electric Oven 50L', 'cooking', null, 'Kitchen Appliances, Ovens', '50 litre electric oven with two hotplates on top.', 'A 50 litre countertop electric oven with a glass door, wire rack and baking tray, plus two sealed hotplates on the top panel. Four dials set temperature, function, timer and the plates.', '[["Capacity","50 litres"],["Hotplates","Two, top mounted"],["Control","Four dials with timer"],["Finish","Matte black"]]'::jsonb, 3, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('blender-3in1', 'GP Multifunctional Blender 3 in 1', 'prep', null, 'Kitchen Appliances, Blenders', 'Stainless base with blending, chopping and milling jars.', 'A complete preparation set on one stainless steel motor base: a tall blending jar, a chopping bowl with blade and a compact mill jar, changed over in a twist. Dial and preset controls on the front.', '[["Jars","Blend, chop, mill"],["Base","Stainless steel"],["Control","Dial and presets"],["Use","Daily food prep"]]'::jsonb, 0, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('blender-4in1', 'GP Multifunctional Blender 4 in 1', 'prep', null, 'Kitchen Appliances, Blenders', 'Four attachments on a single black and chrome base.', 'A four piece set on one rounded motor base: a food processing bowl, a 2 litre measured blending jar, a mill jar and a chopper attachment. Chrome dial control, finished in gloss black.', '[["Attachments","Four"],["Blending jar","2 litres, measured"],["Control","Chrome dial"],["Finish","Gloss black and chrome"]]'::jsonb, 1, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('slow-juicer', 'GP Slow Juicer', 'prep', null, 'Kitchen Appliances, Juicers', 'Cold press juicer with separate juice and pulp containers.', 'A slow cold press juicer that turns fruit and vegetables gently, keeping more of the pulp and flavour in the glass. Wide feed chute, separate juice and pulp containers and a simple two part cleanup.', '[["Method","Cold press"],["Containers","Juice and pulp"],["Feed","Wide chute"],["Finish","Gloss red"]]'::jsonb, 2, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('kettle-2585', 'GP Electric Kettle 2585', 'beverage', null, 'Kitchen Appliances, Jugs & Kettles', 'Insulated electric kettle that holds heat long after boiling.', 'An electric kettle with an insulated flask body, so water stays hot long after it boils. Push top pour, concealed element and a champagne gold finish.', '[["Model","2585"],["Body","Insulated flask"],["Pour","Push top"],["Finish","Champagne gold"]]'::jsonb, 0, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('blender', 'GP Blender', 'prep', null, 'Kitchen Appliances, Blenders', 'Compact counter blender with a clear jar and dial control.', 'A compact everyday blender with a clear measuring jar, sealed lid and a single dial for speed and pulse. Small enough to stay on the counter, strong enough for daily smoothies and sauces.', '[["Jar","Clear, measured"],["Control","Dial with pulse"],["Finish","White and black"],["Use","Smoothies and sauces"]]'::jsonb, 3, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('stand-mixer-12-8l', 'Avinas Stand Mixer 12.8L', 'prep', null, 'Kitchen Appliances, Stand Mixers', 'Tilt head stand mixer with a 12.8 litre stainless bowl.', 'A tilt head stand mixer with a 12.8 litre stainless steel bowl, built for dough, batter and cream in quantity. Whisk, beater and hook attachments with a speed dial on the body.', '[["Bowl","12.8 litres, stainless"],["Head","Tilt back"],["Attachments","Whisk, beater, hook"],["Control","Speed dial"]]'::jsonb, 4, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('fufu-machine-7-5l', 'Avinas Fufu Machine 7.5L', 'prep', null, 'Kitchen Appliances, Fufu Machines', '7.5 litre stainless bowl for pounding fufu at home.', 'A 7.5 litre fufu machine with a stainless steel bowl and a sealed drive head, built to pound cassava and plantain without the mortar. Lift off lid for loading and a wide base that stays put.', '[["Capacity","7.5 litres"],["Bowl","Stainless steel"],["Head","Lift off lid"],["Use","Fufu and heavy dough"]]'::jsonb, 5, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('gas-cooker-50-50', 'GP 50/50 Gas Stove (Model 3000)', 'cooking', null, 'Home Appliances, Cookers', 'Four burner gas stove with an oven and a splash back.', 'A free standing 50 by 50 gas cooker with four burners, a glass front oven below and a folding splash back. Front dial controls and levelling feet, finished in black.', '[["Model","3000"],["Size","50 by 50"],["Burners","Four"],["Oven","Glass front with rack"]]'::jsonb, 4, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('gas-burner-2in1', 'GP Stainless 2 in 1 Gas Burner', 'cooking', null, 'Home Appliances, Gas Burners', 'Table top double burner with a stainless body.', 'A table top gas burner with two independent rings, cast pan supports and a stainless steel body under a printed enamel top. Front dials for each ring, sized to sit on a worktop.', '[["Burners","Two, independent"],["Body","Stainless steel"],["Supports","Cast pan stands"],["Type","Table top"]]'::jsonb, 5, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('hotplate-double', 'Starlux Double Hotplate', 'cooking', null, 'Home Appliances, Hotplates', 'Two sealed electric plates on one low profile body.', 'A double electric hotplate with two sealed cast plates, each on its own dial with an indicator light. A low profile body in brown, for a small kitchen, a hostel room or a back up to gas.', '[["Plates","Two, sealed cast"],["Control","Dial per plate"],["Indicator","Power light"],["Finish","Brown"]]'::jsonb, 6, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('hotplate-single', 'Single Hotplate', 'cooking', null, 'Home Appliances, Hotplates', 'Compact single coil hotplate with a variable dial.', 'A compact single hotplate with an exposed coil element and a variable heat dial, light enough to move and small enough to store. Finished in white with an indicator light.', '[["Plates","One, coil element"],["Control","Variable dial"],["Indicator","Power light"],["Finish","White"]]'::jsonb, 7, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('kettle-2583', 'GP Electric Kettle 2583', 'beverage', null, 'Kitchen Appliances, Jugs & Kettles', 'Insulated kettle with a digital panel and keep warm.', 'An insulated electric kettle with a digital front panel and a flask body that holds temperature after boiling. Push top pour and a concealed element, finished in dark steel.', '[["Model","2583"],["Body","Insulated flask"],["Panel","Digital front"],["Finish","Dark steel"]]'::jsonb, 1, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('flask-3l', 'Flask 3L', 'beverage', null, 'Home & Living, Vacuum Flasks', '3 litre vacuum flask with a cup lid and carry handle.', 'A 3 litre vacuum flask that keeps drinks hot or cold through the day. Screw stopper under a cup lid, a side handle for pouring and a hard outer shell for travel.', '[["Capacity","3 litres"],["Type","Vacuum insulated"],["Lid","Cup top with stopper"],["Handle","Side carry"]]'::jsonb, 2, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('cookware-set-16pc', 'Cookware Set 16 Pieces', 'cookware', 'Cookware', 'Home & Living, Cookware Sets', 'Sixteen piece granite coated set with glass lids.', 'A sixteen piece cookware set in graduated sizes, with a granite effect non stick coating, tempered glass lids and steel rims. Casseroles and a deep pot, stacking down for storage.', '[["Pieces","16"],["Coating","Granite effect non stick"],["Lids","Tempered glass"],["Finish","Copper speckle"]]'::jsonb, 0, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('dinner-set-16pc', 'Melamine Dinner Set 16 Pieces', 'cookware', 'Cookware', 'Home & Living, Dinner Sets', 'Sixteen piece melamine set in a soft blue.', 'A sixteen piece melamine dinner set: square dinner plates, side plates, bowls and mugs in a soft blue. Light to handle, hard wearing and suited to everyday family use.', '[["Pieces","16"],["Material","Melamine"],["Includes","Plates, bowls, mugs"],["Finish","Soft blue"]]'::jsonb, 1, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('kitchen-stand-5-tier', 'Kitchen Stand 5 Tier', 'cookware', 'Cookware', 'Home & Living, Kitchen Storage', 'Five tier folding kitchen rack on castor wheels.', 'A five tier kitchen rack that folds flat for storage and rolls on castor wheels. A powder coated steel frame with mesh shelves, for pots, produce or dry goods in a tight kitchen.', '[["Tiers","Five"],["Frame","Powder coated steel"],["Mobility","Castor wheels"],["Storage","Folds flat"]]'::jsonb, 2, 'setup');
  insert into public.products (id, name, cat, tag, labels, short, descr, spec, sort, updated_by) values ('steam-iron', 'GP Steam Iron V35', 'home', null, 'Home Appliances, Dry & Steam Irons', 'Steam iron with variable control and a large water tank.', 'A steam iron with a non stick soleplate, variable steam and temperature dial, burst and spray functions and a generous water tank, so a full basket of shirts takes one fill.', '[["Model","V35"],["Steam","Variable with burst"],["Soleplate","Non stick, glide"],["Extras","Spray function"]]'::jsonb, 0, 'setup');
  update public.categories set cover = 'microwave-25l' where key = 'cooking' and exists (select 1 from public.products where id = 'microwave-25l');
  update public.categories set cover = 'blender-3in1' where key = 'prep' and exists (select 1 from public.products where id = 'blender-3in1');
  update public.categories set cover = 'kettle-2585' where key = 'beverage' and exists (select 1 from public.products where id = 'kettle-2585');
  update public.categories set cover = 'cookware-set-16pc' where key = 'cookware' and exists (select 1 from public.products where id = 'cookware-set-16pc');
  update public.categories set cover = 'steam-iron' where key = 'home' and exists (select 1 from public.products where id = 'steam-iron');
end $$;
